name: Mend CLI Scan

on:
  workflow_dispatch

jobs:
  build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3
        # Add your package manager build here

        - name: Mend CLI Scan
          env:
            MEND_EMAIL: ${{secrets.MEND_EMAIL}}
            MEND_USER_KEY: ${{secrets.MEND_USER_KEY}}
            MEND_URL: https://saas-eu.mend.io
          run: |
            echo Downloading Mend CLI
            curl https://downloads.mend.io/cli/linux_amd64/mend -o /usr/local/bin/mend && chmod +x /usr/local/bin/mend
            echo Start Mend CLI scan
            ./mend dep -u -s "Luke Brogan Demo - Github.com//GitHubActions//Easybuggy" --reachability
            ./mend code -s "Luke Brogan Demo - Github.com//GitHubActions//Easybuggy" --remediate
            ./mend image cytopia/dvwa
