name: Mend CLI Scan

on:
  workflow_dispatch

jobs:
  build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
        # Add your package manager build here

        - name: Mend CLI Scan
          env:
            #SCA
            MEND_EMAIL: ${{secrets.MEND_SCA_EMAIL}}
            MEND_USER_KEY: ${{secrets.MEND_SCA_USERKEY}}
            MEND_URL: https://saas-eu.mend.io
            #SAST
            MEND_SAST_SERVER_URL: https://saas-eu.mend.io/sast
            MEND_SAST_API_TOKEN: ${{secrets.MEND_SAST_API}}
            MEND_SAST_ORGANIZATION: ${{secrets.MEND_SAST_ORGANIZATION}}
          run: |
            echo Downloading Mend CLI
            curl -LJO https://downloads.mend.io/production/unified/latest/linux_amd64/mend && chmod +x mend
            echo Start Mend CLI scan
            ./mend dep -u
            ./mend code -j 2 --remediate
            ./mend image ubuntu:latest
